### Rota inicial
GET http://localhost:3000/

### Listar todos os filmes
GET http://localhost:3000/filmes

### Cadastrar novo filme
POST http://localhost:3000/filmes
Content-Type: application/json

{
  "titulo": "Matrix",
  "genero": "Ficção",
  "midia": "Blu-Ray"
}

### Buscar filme por ID
GET http://localhost:3000/filmes/1

### Atualizar filme existente
PUT http://localhost:3000/filmes/1
Content-Type: application/json

{
  "titulo": "Matrix Reloaded",
  "genero": "Ação",
  "midia": "DVD"
}

### Deletar filme
DELETE http://localhost:3000/filmes/1

### Listar novamente os filmes (verificar se foi removido)
GET http://localhost:3000/filmes
